### ISSUE TITLE
프론트엔드 컴포넌트 설계

### ISSUE THREAD

**Issue by SeungWookHan** [Lenend-KPU/LBS-Platform#9]
- [x] IA, 화면흐름도에 따른 컴포넌트 설계
- [x] 시각화

**Comment by ChanHeee** [comment]
![컴포넌트_구조](https://user-images.githubusercontent.com/19974384/113512488-d2912b80-959f-11eb-9d5a-ca85d3bd3925.PNG)
![컴포넌트_설명](https://user-images.githubusercontent.com/19974384/113512492-d4f38580-959f-11eb-8137-a34b62e8fb08.PNG)

**Comment by SeungWookHan** [comment]
2차 스프린트로 넘어감
